CREATE TABLE `t_custumer_type` (
	`id` INT(11) NOT NULL,
	`cst_type` INT(11) NOT NULL COMMENT '客户类型编码',
	`cst_type_name` VARCHAR(20) NOT NULL COMMENT '客户类型名称',
	`note` VARCHAR(40) NOT NULL COMMENT '客户类型备注',
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '客户类型创建时间',
	`update_time` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '客户类型修改时间',
	PRIMARY KEY (`id`),
	UNIQUE INDEX `Idx_type` (`cst_type`)
)
COMMENT='客户类型'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;



CREATE TABLE `t_customer` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`cst_seq` VARCHAR(20) NOT NULL DEFAULT '0' COMMENT '客户流水号',
	`cst_number` VARCHAR(20) NOT NULL DEFAULT '0' COMMENT '客户编号',
	`name` VARCHAR(40) NOT NULL DEFAULT '' COMMENT '客户名称',
	`status` SMALLINT(6) NOT NULL DEFAULT '0' COMMENT '客户状态',
	`cst_type` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '客户类型',
	`cst_character` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '客户性质',
	`cst_group` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '客户所属集团',
	`district` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '所属片区',
	`contacts` VARCHAR(20) NOT NULL DEFAULT '0' COMMENT '送气实际联系人',
	`cat_phone` VARCHAR(11) NOT NULL DEFAULT '0' COMMENT '送气实际联系电话',
	`phone_1` VARCHAR(11) NOT NULL DEFAULT '0' COMMENT '客户电话1',
	`phone_2` VARCHAR(11) NOT NULL DEFAULT '0' COMMENT '客户电话2',
	`phone_3` VARCHAR(11) NOT NULL DEFAULT '0' COMMENT '客户电话3',
	`addr` VARCHAR(50) NOT NULL DEFAULT '0' COMMENT '客户地址',
	`floor` SMALLINT(6) NOT NULL DEFAULT '0' COMMENT '客户楼层',
	`source` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '客户来源',
	`note` VARCHAR(50) NOT NULL DEFAULT '0' COMMENT '备注',
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '开户时间',
	`update_time` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '资料修改时间',
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `Idx_name` (`name`)
)
COMMENT='客户信息表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
